### ISSUE TITLE
remove anomalous FS rxGain check

### ISSUE THREAD

**Issue by mmandellrkf** [open-afc-project/openafc#102]
When reading FS data, gain values less than 10 dB are considered anomalous.  This should be removed and the afc-engine should use whatever is in the FS database.

**Comment by farinazedalat** [comment]
Ran a test (all the relevant files attached here) and confirmed that the fs_anom.csv file is empty as expected. Previously, this file contained 23 links for this test that were removed by afc-engine 
[102tests.zip](https://github.com/user-attachments/files/16089259/102tests.zip)
due to having Rx Gain of 6 dBi).
