### ISSUE TITLE
fix exc_thr file

### ISSUE THREAD

**Issue by mmandellrkf** [open-afc-project/openafc#105]
Code modifications to the afc-engine that optimize speed performance broke the exc_thr file.  The underlying issue is that printing to the exc_thr will require re-computation of some parameters and thus undermine the optimizations to some extent.  It is expected that in a production environment, the visibility threshold will be set high enough so additional calculations done when printing to the exc_thr file have negligible impact on execution speed.  For debugging a specific case, execution speed is not critical, and the visibility threshold can be set lower value resulting in a larger, more extensive, exc_thr file.

**Comment by farinazedalat** [comment]
Validated that the updated exc_thr would show the links with distance > 1km using ITM (rather the FSPL that was tried originally to determine whether the regulatory threshold is exceeded or not). When printSkippedLinks flag in AFC Config is set, links that pass the regulatory threshold with FSPL are shown as well. Note that when the printSkippedLinks flag is set to false, links that should be using FSPL (i.e. 30m distance or inside AP uncertainty footprint) are still shown. Attached test case shows that the exc_thr files with this flag set or not are
[105test_FSPL1modified.zip](https://github.com/user-attachments/files/16168461/105test_FSPL1modified.zip)
 correct.

**Comment by farinazedalat** [comment]
As noted in the C++ code:  
When _printSkippedLinksFlag set, links analyzed with FSPL that are NOT subsequently analyzed with ITM are inserted into the exc_thr file.  The skip flag means the current FSPL result is not used to update min EIRP.  This occurs whenever FSPL is used, except when distance < 30m and contains2D is true in which case FSPL is forced.  When FSPL limits the EIRP calculation, the FSPL result is skipped because ITM will subsequently be calculated.  When FSPL does not limit the EIRP calculation, the FSPL results is skipped because they don't affect the result and it is not necessary to run ITM.  The flag _printSkippedLinksFlag is not a good name as it refers to printing FSPL results that are not recalculated with ITM and not the skip parameter.  Setting _printSkippedLinksFlag is useful for testing and debugging, however, the extra printing impacts execution speed.
