### ISSUE TITLE
ERROR: CachedGdalBase::initialize(): GDAL data directory '/mnt/nfs/rat_transfer/3dep/1_arcsec' does not contain files matching fnmatch pattern 'USGS_1_[ns][0-9][0-9][ew][0-9][0-9][0-9].tif'

### ISSUE THREAD

**Issue by sambk** [open-afc-project/openafc#197]
Hi Openafc team,
After passing some errors by creating some database files according to database_readme.md, I run into this error when requesting an availableSpectrumInquiry:

> Failed to initialize databases: ERROR: CachedGdalBase::initialize(): GDAL data directory '/mnt/nfs/rat_transfer/3dep/1_arcsec' does not contain files matching fnmatch pattern 'USGS_1_[ns][0-9][0-9][ew][0-9][0-9][0-9].tif'

Looks like some files in 3dep/1_arcsec/ folder are missing but I'm not sure how to create them. I've tried downloading https://data.globalchange.gov/dataset/usgs-national-elevation-dataset-ned-1-arc-second in json format and place it in /3dep/1_arcsec/ but it does not work.

I really appreciate any support!
Thanks!

**Comment by farinazedalat** [comment]
Hello, 
We looked into this issue. It appears that the latest 3DEP database from USGS has different filename convention that is not currently supported by OpenAFC. This will be supported in the future when the database is updated to the latest version.

In the meantime, you can download the 3DEP files from WFA's github (https://github.com/Wi-FiTestSuite/6GHz-AFC/tree/main/3Dep) since this is the set that would be needed to run the lab testing certification.

As a temporary measure, you can use these files as is (in the native NAD83/NAVD88 format). We are currently working on automating the conversion of these files to WGS84 format. 

Hope this works.

**Comment by farinazedalat** [comment]
Also, we downloaded our native 3DEP files from here: https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/1/TIFF/current/

**Comment by sambk** [comment]
Hi,
It works after I download these files. 
Thank you for your support!

**Comment by sambk** [comment]
Hi @farinazedalat,
I would like to reopen this to confirm this question:
**Do I need to convert these files to WGS84 according to this guideline: https://github.com/open-afc-project/openafc/tree/main/tools/geo_converters#usacanadamexico-3dep-terrain-model- ?**

Although it works, this guideline makes me confused that if it work properly?

Thanks,
Pham Viet Sam

**Comment by farinazedalat** [comment]
Please wait on doing the conversion. The database readme file will be updated when Issue 135 is pushed (which should be any day this week) that will have more clear instructions on doing this conversion. Once you have done that, we can compare our md5sums.

**Comment by sambk** [comment]
Thanks for your information. I will wait for the commit
