### ISSUE TITLE
polygon bug

### ISSUE THREAD

**Issue by mmandellrkf** [open-afc-project/openafc#49]
Bug in polygon calculation where integer calculation overflows 32 bits.

**Comment by farinazedalat** [comment]
The following lat/long: 42.0054, -87.7329 was identified by AFC Engine to be outside the country (US) boundary (US.kml) even though this was inside it. The root cause of this issue was the low precision of the boundary (as 32-bit integer was used). When the precision was increased to 64 bits, this was resolved and this lat/long was correctly detected by AFC Engine to be inside the country boundary.
